### ISSUE TITLE
Recovering Inferred types does not work

### ISSUE THREAD

**Issue by W95Psp** [W95Psp/CleanForVSCode#1] opened 2017-10-10 09:15 UTC
CPM seems to ignore the ListTypes directive in Modules.
Hence, I can't recover any longer any type information.
(Before, I used to run `clm -lat {target icl file}`, that output type info)

**Comment by camilstaps** [comment] 2017-10-12 10:34
I believe the `ListTypes` entry should be in a `MainModule/Compiler` block, e.g.:

```
MainModule
	Name:	test
	Dir:	{Project}
	Compiler
		ListTypes:	StrictExportTypes
```

**Comment by W95Psp** [comment] 2017-10-12 11:03
Yes, that what I do, actually; but even with this setting, it's not outputting any types, either using linux CPM or windows CPM.
I tried to use CleanIDE just to check whether it was outputting types according prj file, and it works as expected, but I have no idea how it internally works.

Oh and maybe you could help me with something not linked to that: each time I `cpm make` a project, everything is recompiled (like each single iTasks/Sapl/Std* modules, it says `[some.module.path]: is older than .abc file`). Do you think it's a configuration issue?

**Comment by camilstaps** [comment] 2017-10-12 11:37
Ah, you're right, that does not appear to be implemented; the `compiler_arguments` and `makeCompilerOptionsArguments` functions in [`PmCleanSystem`](https://svn.cs.ru.nl/repos/clean-ide/trunk/Unix/PmCleanSystem.icl) do not have options for `-lat`, even though the project file is parsed correctly.

For the recompilation problem: does it help if you set `Dynamics` to `True` in the project file (Global/Application/Profile/Dynamics)? I'm not sure if it's by design that that is required.

**Comment by W95Psp** [comment] 2017-10-15 09:38
Ah okay, that makes sense!

Oh, yes, it compiles in few seconds now, that's much nicer, thank you ! :)

**Comment by camilstaps** [comment] 2018-12-15 12:01
The StrictExportTypes issue in cpm has been fixed now.

**Closed as completed** 2018-12-23 15:27 UTC
